// utils/chinaCities.js

export const CITY_DATA = [
  // 直辖市
  { name: '北京', pinyin: 'beijing', firstLetter: 'B' },
  { name: '上海', pinyin: 'shanghai', firstLetter: 'S' },
  { name: '天津', pinyin: 'tianjin', firstLetter: 'T' },
  { name: '重庆', pinyin: 'chongqing', firstLetter: 'C' },

  // 河北省
  { name: '石家庄', pinyin: 'shijiazhuang', firstLetter: 'S' },
  { name: '唐山', pinyin: 'tangshan', firstLetter: 'T' },
  { name: '秦皇岛', pinyin: 'qinhuangdao', firstLetter: 'Q' },
  { name: '邯郸', pinyin: 'handan', firstLetter: 'H' },
  { name: '邢台', pinyin: 'xingtai', firstLetter: 'X' },
  { name: '保定', pinyin: 'baoding', firstLetter: 'B' },
  { name: '张家口', pinyin: 'zhangjiakou', firstLetter: 'Z' },
  { name: '承德', pinyin: 'chengde', firstLetter: 'C' },
  { name: '沧州', pinyin: 'cangzhou', firstLetter: 'C' },
  { name: '廊坊', pinyin: 'langfang', firstLetter: 'L' },
  { name: '衡水', pinyin: 'hengshui', firstLetter: 'H' },

  // 山西省
  { name: '太原', pinyin: 'taiyuan', firstLetter: 'T' },
  { name: '大同', pinyin: 'datong', firstLetter: 'D' },
  { name: '阳泉', pinyin: 'yangquan', firstLetter: 'Y' },
  { name: '长治', pinyin: 'changzhi', firstLetter: 'C' },
  { name: '晋城', pinyin: 'jincheng', firstLetter: 'J' },
  { name: '朔州', pinyin: 'shuozhou', firstLetter: 'S' },
  { name: '晋中', pinyin: 'jinzhong', firstLetter: 'J' },
  { name: '运城', pinyin: 'yuncheng', firstLetter: 'Y' },
  { name: '忻州', pinyin: 'xinzhou', firstLetter: 'X' },
  { name: '临汾', pinyin: 'linfen', firstLetter: 'L' },
  { name: '吕梁', pinyin: 'lvliang', firstLetter: 'L' },

  // 内蒙古
  { name: '呼和浩特', pinyin: 'huhehaote', firstLetter: 'H' },
  { name: '包头', pinyin: 'baotou', firstLetter: 'B' },
  { name: '乌海', pinyin: 'wuhai', firstLetter: 'W' },
  { name: '赤峰', pinyin: 'chifeng', firstLetter: 'C' },
  { name: '通辽', pinyin: 'tongliao', firstLetter: 'T' },
  { name: '鄂尔多斯', pinyin: 'eerduosi', firstLetter: 'E' },
  { name: '呼伦贝尔', pinyin: 'hulunbeier', firstLetter: 'H' },
  { name: '巴彦淖尔', pinyin: 'bayannaoer', firstLetter: 'B' },
  { name: '乌兰察布', pinyin: 'wulanchabu', firstLetter: 'W' },

  // 辽宁省
  { name: '沈阳', pinyin: 'shenyang', firstLetter: 'S' },
  { name: '大连', pinyin: 'dalian', firstLetter: 'D' },
  { name: '鞍山', pinyin: 'anshan', firstLetter: 'A' },
  { name: '抚顺', pinyin: 'fushun', firstLetter: 'F' },
  { name: '本溪', pinyin: 'benxi', firstLetter: 'B' },
  { name: '丹东', pinyin: 'dandong', firstLetter: 'D' },
  { name: '锦州', pinyin: 'jinzhou', firstLetter: 'J' },
  { name: '营口', pinyin: 'yingkou', firstLetter: 'Y' },
  { name: '阜新', pinyin: 'fuxin', firstLetter: 'F' },
  { name: '辽阳', pinyin: 'liaoyang', firstLetter: 'L' },
  { name: '盘锦', pinyin: 'panjin', firstLetter: 'P' },
  { name: '铁岭', pinyin: 'tieling', firstLetter: 'T' },
  { name: '朝阳', pinyin: 'chaoyang', firstLetter: 'C' },
  { name: '葫芦岛', pinyin: 'huludao', firstLetter: 'H' },

  // 吉林省
  { name: '长春', pinyin: 'changchun', firstLetter: 'C' },
  { name: '吉林', pinyin: 'jilin', firstLetter: 'J' },
  { name: '四平', pinyin: 'siping', firstLetter: 'S' },
  { name: '辽源', pinyin: 'liaoyuan', firstLetter: 'L' },
  { name: '通化', pinyin: 'tonghua', firstLetter: 'T' },
  { name: '白山', pinyin: 'baishan', firstLetter: 'B' },
  { name: '松原', pinyin: 'songyuan', firstLetter: 'S' },
  { name: '白城', pinyin: 'baicheng', firstLetter: 'B' },
  { name: '延边', pinyin: 'yanbian', firstLetter: 'Y' },

  // 黑龙江省
  { name: '哈尔滨', pinyin: 'haerbin', firstLetter: 'H' },
  { name: '齐齐哈尔', pinyin: 'qiqihaer', firstLetter: 'Q' },
  { name: '鸡西', pinyin: 'jixi', firstLetter: 'J' },
  { name: '鹤岗', pinyin: 'hegang', firstLetter: 'H' },
  { name: '双鸭山', pinyin: 'shuangyashan', firstLetter: 'S' },
  { name: '大庆', pinyin: 'daqing', firstLetter: 'D' },
  { name: '伊春', pinyin: 'yichun', firstLetter: 'Y' },
  { name: '佳木斯', pinyin: 'jiamusi', firstLetter: 'J' },
  { name: '七台河', pinyin: 'qitaihe', firstLetter: 'Q' },
  { name: '牡丹江', pinyin: 'mudanjiang', firstLetter: 'M' },
  { name: '黑河', pinyin: 'heihe', firstLetter: 'H' },
  { name: '绥化', pinyin: 'suihua', firstLetter: 'S' },
  { name: '大兴安岭', pinyin: 'daxinganling', firstLetter: 'D' },

  // 江苏省
  { name: '南京', pinyin: 'nanjing', firstLetter: 'N' },
  { name: '无锡', pinyin: 'wuxi', firstLetter: 'W' },
  { name: '徐州', pinyin: 'xuzhou', firstLetter: 'X' },
  { name: '常州', pinyin: 'changzhou', firstLetter: 'C' },
  { name: '苏州', pinyin: 'suzhou', firstLetter: 'S' },
  { name: '南通', pinyin: 'nantong', firstLetter: 'N' },
  { name: '连云港', pinyin: 'lianyungang', firstLetter: 'L' },
  { name: '淮安', pinyin: 'huaian', firstLetter: 'H' },
  { name: '盐城', pinyin: 'yancheng', firstLetter: 'Y' },
  { name: '扬州', pinyin: 'yangzhou', firstLetter: 'Y' },
  { name: '镇江', pinyin: 'zhenjiang', firstLetter: 'Z' },
  { name: '泰州', pinyin: 'taizhou', firstLetter: 'T' },
  { name: '宿迁', pinyin: 'suqian', firstLetter: 'S' },

  // 浙江省
  { name: '杭州', pinyin: 'hangzhou', firstLetter: 'H' },
  { name: '宁波', pinyin: 'ningbo', firstLetter: 'N' },
  { name: '温州', pinyin: 'wenzhou', firstLetter: 'W' },
  { name: '嘉兴', pinyin: 'jiaxing', firstLetter: 'J' },
  { name: '湖州', pinyin: 'huzhou', firstLetter: 'H' },
  { name: '绍兴', pinyin: 'shaoxing', firstLetter: 'S' },
  { name: '金华', pinyin: 'jinhua', firstLetter: 'J' },
  { name: '衢州', pinyin: 'quzhou', firstLetter: 'Q' },
  { name: '舟山', pinyin: 'zhoushan', firstLetter: 'Z' },
  { name: '台州', pinyin: 'taizhou', firstLetter: 'T' },
  { name: '丽水', pinyin: 'lishui', firstLetter: 'L' },

  // 安徽省
  { name: '合肥', pinyin: 'hefei', firstLetter: 'H' },
  { name: '芜湖', pinyin: 'wuhu', firstLetter: 'W' },
  { name: '蚌埠', pinyin: 'bengbu', firstLetter: 'B' },
  { name: '淮南', pinyin: 'huainan', firstLetter: 'H' },
  { name: '马鞍山', pinyin: 'maanshan', firstLetter: 'M' },
  { name: '淮北', pinyin: 'huaibei', firstLetter: 'H' },
  { name: '铜陵', pinyin: 'tongling', firstLetter: 'T' },
  { name: '安庆', pinyin: 'anqing', firstLetter: 'A' },
  { name: '黄山', pinyin: 'huangshan', firstLetter: 'H' },
  { name: '滁州', pinyin: 'chuzhou', firstLetter: 'C' },
  { name: '阜阳', pinyin: 'fuyang', firstLetter: 'F' },
  { name: '宿州', pinyin: 'suzhou', firstLetter: 'S' },
  { name: '六安', pinyin: 'luan', firstLetter: 'L' },
  { name: '亳州', pinyin: 'bozhou', firstLetter: 'B' },
  { name: '池州', pinyin: 'chizhou', firstLetter: 'C' },
  { name: '宣城', pinyin: 'xuancheng', firstLetter: 'X' },

  // 福建省
  { name: '福州', pinyin: 'fuzhou', firstLetter: 'F' },
  { name: '厦门', pinyin: 'xiamen', firstLetter: 'X' },
  { name: '莆田', pinyin: 'putian', firstLetter: 'P' },
  { name: '三明', pinyin: 'sanming', firstLetter: 'S' },
  { name: '泉州', pinyin: 'quanzhou', firstLetter: 'Q' },
  { name: '漳州', pinyin: 'zhangzhou', firstLetter: 'Z' },
  { name: '南平', pinyin: 'nanping', firstLetter: 'N' },
  { name: '龙岩', pinyin: 'longyan', firstLetter: 'L' },
  { name: '宁德', pinyin: 'ningde', firstLetter: 'N' },

  // 江西省
  { name: '南昌', pinyin: 'nanchang', firstLetter: 'N' },
  { name: '景德镇', pinyin: 'jingdezhen', firstLetter: 'J' },
  { name: '萍乡', pinyin: 'pingxiang', firstLetter: 'P' },
  { name: '九江', pinyin: 'jiujiang', firstLetter: 'J' },
  { name: '新余', pinyin: 'xinyu', firstLetter: 'X' },
  { name: '鹰潭', pinyin: 'yingtan', firstLetter: 'Y' },
  { name: '赣州', pinyin: 'ganzhou', firstLetter: 'G' },
  { name: '吉安', pinyin: 'jian', firstLetter: 'J' },
  { name: '宜春', pinyin: 'yichun', firstLetter: 'Y' },
  { name: '抚州', pinyin: 'fuzhou', firstLetter: 'F' },
  { name: '上饶', pinyin: 'shangrao', firstLetter: 'S' },

  // 山东省
  { name: '济南', pinyin: 'jinan', firstLetter: 'J' },
  { name: '青岛', pinyin: 'qingdao', firstLetter: 'Q' },
  { name: '淄博', pinyin: 'zibo', firstLetter: 'Z' },
  { name: '枣庄', pinyin: 'zaozhuang', firstLetter: 'Z' },
  { name: '东营', pinyin: 'dongying', firstLetter: 'D' },
  { name: '烟台', pinyin: 'yantai', firstLetter: 'Y' },
  { name: '潍坊', pinyin: 'weifang', firstLetter: 'W' },
  { name: '济宁', pinyin: 'jining', firstLetter: 'J' },
  { name: '泰安', pinyin: 'taian', firstLetter: 'T' },
  { name: '威海', pinyin: 'weihai', firstLetter: 'W' },
  { name: '日照', pinyin: 'rizhao', firstLetter: 'R' },
  { name: '临沂', pinyin: 'linyi', firstLetter: 'L' },
  { name: '德州', pinyin: 'dezhou', firstLetter: 'D' },
  { name: '聊城', pinyin: 'liaocheng', firstLetter: 'L' },
  { name: '滨州', pinyin: 'binzhou', firstLetter: 'B' },
  { name: '菏泽', pinyin: 'heze', firstLetter: 'H' },

  // 河南省
  { name: '郑州', pinyin: 'zhengzhou', firstLetter: 'Z' },
  { name: '开封', pinyin: 'kaifeng', firstLetter: 'K' },
  { name: '洛阳', pinyin: 'luoyang', firstLetter: 'L' },
  { name: '平顶山', pinyin: 'pingdingshan', firstLetter: 'P' },
  { name: '安阳', pinyin: 'anyang', firstLetter: 'A' },
  { name: '鹤壁', pinyin: 'hebi', firstLetter: 'H' },
  { name: '新乡', pinyin: 'xinxiang', firstLetter: 'X' },
  { name: '焦作', pinyin: 'jiaozuo', firstLetter: 'J' },
  { name: '濮阳', pinyin: 'puyang', firstLetter: 'P' },
  { name: '许昌', pinyin: 'xuchang', firstLetter: 'X' },
  { name: '漯河', pinyin: 'luohe', firstLetter: 'L' },
  { name: '三门峡', pinyin: 'sanmenxia', firstLetter: 'S' },
  { name: '南阳', pinyin: 'nanyang', firstLetter: 'N' },
  { name: '商丘', pinyin: 'shangqiu', firstLetter: 'S' },
  { name: '信阳', pinyin: 'xinyang', firstLetter: 'X' },
  { name: '周口', pinyin: 'zhoukou', firstLetter: 'Z' },
  { name: '驻马店', pinyin: 'zhumadian', firstLetter: 'Z' },

  // 湖北省
  { name: '武汉', pinyin: 'wuhan', firstLetter: 'W' },
  { name: '黄石', pinyin: 'huangshi', firstLetter: 'H' },
  { name: '十堰', pinyin: 'shiyan', firstLetter: 'S' },
  { name: '宜昌', pinyin: 'yichang', firstLetter: 'Y' },
  { name: '襄阳', pinyin: 'xiangyang', firstLetter: 'X' },
  { name: '鄂州', pinyin: 'ezhou', firstLetter: 'E' },
  { name: '荆门', pinyin: 'jingmen', firstLetter: 'J' },
  { name: '孝感', pinyin: 'xiaogan', firstLetter: 'X' },
  { name: '荆州', pinyin: 'jingzhou', firstLetter: 'J' },
  { name: '黄冈', pinyin: 'huanggang', firstLetter: 'H' },
  { name: '咸宁', pinyin: 'xianning', firstLetter: 'X' },
  { name: '随州', pinyin: 'suizhou', firstLetter: 'S' },
  { name: '恩施', pinyin: 'enshi', firstLetter: 'E' },

  // 湖南省
  { name: '长沙', pinyin: 'changsha', firstLetter: 'C' },
  { name: '株洲', pinyin: 'zhuzhou', firstLetter: 'Z' },
  { name: '湘潭', pinyin: 'xiangtan', firstLetter: 'X' },
  { name: '衡阳', pinyin: 'hengyang', firstLetter: 'H' },
  { name: '邵阳', pinyin: 'shaoyang', firstLetter: 'S' },
  { name: '岳阳', pinyin: 'yueyang', firstLetter: 'Y' },
  { name: '常德', pinyin: 'changde', firstLetter: 'C' },
  { name: '张家界', pinyin: 'zhangjiajie', firstLetter: 'Z' },
  { name: '益阳', pinyin: 'yiyang', firstLetter: 'Y' },
  { name: '郴州', pinyin: 'chenzhou', firstLetter: 'C' },
  { name: '永州', pinyin: 'yongzhou', firstLetter: 'Y' },
  { name: '怀化', pinyin: 'huaihua', firstLetter: 'H' },
  { name: '娄底', pinyin: 'loudi', firstLetter: 'L' },
  { name: '湘西', pinyin: 'xiangxi', firstLetter: 'X' },

  // 广东省
  { name: '广州', pinyin: 'guangzhou', firstLetter: 'G' },
  { name: '韶关', pinyin: 'shaoguan', firstLetter: 'S' },
  { name: '深圳', pinyin: 'shenzhen', firstLetter: 'S' },
  { name: '珠海', pinyin: 'zhuhai', firstLetter: 'Z' },
  { name: '汕头', pinyin: 'shantou', firstLetter: 'S' },
  { name: '佛山', pinyin: 'foshan', firstLetter: 'F' },
  { name: '江门', pinyin: 'jiangmen', firstLetter: 'J' },
  { name: '湛江', pinyin: 'zhanjiang', firstLetter: 'Z' },
  { name: '茂名', pinyin: 'maoming', firstLetter: 'M' },
  { name: '肇庆', pinyin: 'zhaoqing', firstLetter: 'Z' },
  { name: '惠州', pinyin: 'huizhou', firstLetter: 'H' },
  { name: '梅州', pinyin: 'meizhou', firstLetter: 'M' },
  { name: '汕尾', pinyin: 'shanwei', firstLetter: 'S' },
  { name: '河源', pinyin: 'heyuan', firstLetter: 'H' },
  { name: '阳江', pinyin: 'yangjiang', firstLetter: 'Y' },
  { name: '清远', pinyin: 'qingyuan', firstLetter: 'Q' },
  { name: '东莞', pinyin: 'dongguan', firstLetter: 'D' },
  { name: '中山', pinyin: 'zhongshan', firstLetter: 'Z' },
  { name: '潮州', pinyin: 'chaozhou', firstLetter: 'C' },
  { name: '揭阳', pinyin: 'jieyang', firstLetter: 'J' },
  { name: '云浮', pinyin: 'yunfu', firstLetter: 'Y' },

  // 广西
  { name: '南宁', pinyin: 'nanning', firstLetter: 'N' },
  { name: '柳州', pinyin: 'liuzhou', firstLetter: 'L' },
  { name: '桂林', pinyin: 'guilin', firstLetter: 'G' },
  { name: '梧州', pinyin: 'wuzhou', firstLetter: 'W' },
  { name: '北海', pinyin: 'beihai', firstLetter: 'B' },
  { name: '防城港', pinyin: 'fangchenggang', firstLetter: 'F' },
  { name: '钦州', pinyin: 'qinzhou', firstLetter: 'Q' },
  { name: '贵港', pinyin: 'guigang', firstLetter: 'G' },
  { name: '玉林', pinyin: 'yulin', firstLetter: 'Y' },
  { name: '百色', pinyin: 'baise', firstLetter: 'B' },
  { name: '贺州', pinyin: 'hezhou', firstLetter: 'H' },
  { name: '河池', pinyin: 'hechi', firstLetter: 'H' },
  { name: '来宾', pinyin: 'laibin', firstLetter: 'L' },
  { name: '崇左', pinyin: 'chongzuo', firstLetter: 'C' },

  // 海南省
  { name: '海口', pinyin: 'haikou', firstLetter: 'H' },
  { name: '三亚', pinyin: 'sanya', firstLetter: 'S' },
  { name: '三沙', pinyin: 'sansha', firstLetter: 'S' },
  { name: '儋州', pinyin: 'danzhou', firstLetter: 'D' },

  // 四川省
  { name: '成都', pinyin: 'chengdu', firstLetter: 'C' },
  { name: '自贡', pinyin: 'zigong', firstLetter: 'Z' },
  { name: '攀枝花', pinyin: 'panzhihua', firstLetter: 'P' },
  { name: '泸州', pinyin: 'luzhou', firstLetter: 'L' },
  { name: '德阳', pinyin: 'deyang', firstLetter: 'D' },
  { name: '绵阳', pinyin: 'mianyang', firstLetter: 'M' },
  { name: '广元', pinyin: 'guangyuan', firstLetter: 'G' },
  { name: '遂宁', pinyin: 'suining', firstLetter: 'S' },
  { name: '内江', pinyin: 'neijiang', firstLetter: 'N' },
  { name: '乐山', pinyin: 'leshan', firstLetter: 'L' },
  { name: '南充', pinyin: 'nanchong', firstLetter: 'N' },
  { name: '眉山', pinyin: 'meishan', firstLetter: 'M' },
  { name: '宜宾', pinyin: 'yibin', firstLetter: 'Y' },
  { name: '广安', pinyin: 'guangan', firstLetter: 'G' },
  { name: '达州', pinyin: 'dazhou', firstLetter: 'D' },
  { name: '雅安', pinyin: 'yaan', firstLetter: 'Y' },
  { name: '巴中', pinyin: 'bazhong', firstLetter: 'B' },
  { name: '资阳', pinyin: 'ziyang', firstLetter: 'Z' },
  { name: '阿坝', pinyin: 'aba', firstLetter: 'A' },
  { name: '甘孜', pinyin: 'ganzi', firstLetter: 'G' },
  { name: '凉山', pinyin: 'liangshan', firstLetter: 'L' },

  // 贵州省
  { name: '贵阳', pinyin: 'guiyang', firstLetter: 'G' },
  { name: '六盘水', pinyin: 'liupanshui', firstLetter: 'L' },
  { name: '遵义', pinyin: 'zunyi', firstLetter: 'Z' },
  { name: '安顺', pinyin: 'anshun', firstLetter: 'A' },
  { name: '毕节', pinyin: 'bijie', firstLetter: 'B' },
  { name: '铜仁', pinyin: 'tongren', firstLetter: 'T' },
  { name: '黔西南', pinyin: 'qianxinan', firstLetter: 'Q' },
  { name: '黔东南', pinyin: 'qiandongnan', firstLetter: 'Q' },
  { name: '黔南', pinyin: 'qiannan', firstLetter: 'Q' },

  // 云南省
  { name: '昆明', pinyin: 'kunming', firstLetter: 'K' },
  { name: '曲靖', pinyin: 'qujing', firstLetter: 'Q' },
  { name: '玉溪', pinyin: 'yuxi', firstLetter: 'Y' },
  { name: '保山', pinyin: 'baoshan', firstLetter: 'B' },
  { name: '昭通', pinyin: 'zhaotong', firstLetter: 'Z' },
  { name: '丽江', pinyin: 'lijiang', firstLetter: 'L' },
  { name: '普洱', pinyin: 'puer', firstLetter: 'P' },
  { name: '临沧', pinyin: 'lincang', firstLetter: 'L' },
  { name: '楚雄', pinyin: 'chuxiong', firstLetter: 'C' },
  { name: '红河', pinyin: 'honghe', firstLetter: 'H' },
  { name: '文山', pinyin: 'wenshan', firstLetter: 'W' },
  { name: '西双版纳', pinyin: 'xishuangbanna', firstLetter: 'X' },
  { name: '大理', pinyin: 'dali', firstLetter: 'D' },
  { name: '德宏', pinyin: 'dehong', firstLetter: 'D' },
  { name: '怒江', pinyin: 'nujiang', firstLetter: 'N' },
  { name: '迪庆', pinyin: 'diqing', firstLetter: 'D' },

  // 西藏
  { name: '拉萨', pinyin: 'lasa', firstLetter: 'L' },
  { name: '日喀则', pinyin: 'rikaze', firstLetter: 'R' },
  { name: '昌都', pinyin: 'changdu', firstLetter: 'C' },
  { name: '林芝', pinyin: 'linzhi', firstLetter: 'L' },
  { name: '山南', pinyin: 'shannan', firstLetter: 'S' },
  { name: '那曲', pinyin: 'naqu', firstLetter: 'N' },
  { name: '阿里', pinyin: 'ali', firstLetter: 'A' },

  // 陕西省
  { name: '西安', pinyin: 'xian', firstLetter: 'X' },
  { name: '铜川', pinyin: 'tongchuan', firstLetter: 'T' },
  { name: '宝鸡', pinyin: 'baoji', firstLetter: 'B' },
  { name: '咸阳', pinyin: 'xianyang', firstLetter: 'X' },
  { name: '渭南', pinyin: 'weinan', firstLetter: 'W' },
  { name: '延安', pinyin: 'yanan', firstLetter: 'Y' },
  { name: '汉中', pinyin: 'hanzhong', firstLetter: 'H' },
  { name: '榆林', pinyin: 'yulin', firstLetter: 'Y' },
  { name: '安康', pinyin: 'ankang', firstLetter: 'A' },
  { name: '商洛', pinyin: 'shangluo', firstLetter: 'S' },

  // 甘肃省
  { name: '兰州', pinyin: 'lanzhou', firstLetter: 'L' },
  { name: '嘉峪关', pinyin: 'jiayuguan', firstLetter: 'J' },
  { name: '金昌', pinyin: 'jinchang', firstLetter: 'J' },
  { name: '白银', pinyin: 'baiyin', firstLetter: 'B' },
  { name: '天水', pinyin: 'tianshui', firstLetter: 'T' },
  { name: '武威', pinyin: 'wuwei', firstLetter: 'W' },
  { name: '张掖', pinyin: 'zhangye', firstLetter: 'Z' },
  { name: '平凉', pinyin: 'pingliang', firstLetter: 'P' },
  { name: '酒泉', pinyin: 'jiuquan', firstLetter: 'J' },
  { name: '庆阳', pinyin: 'qingyang', firstLetter: 'Q' },
  { name: '定西', pinyin: 'dingxi', firstLetter: 'D' },
  { name: '陇南', pinyin: 'longnan', firstLetter: 'L' },
  { name: '临夏', pinyin: 'linxia', firstLetter: 'L' },
  { name: '甘南', pinyin: 'gannan', firstLetter: 'G' },

  // 青海省
  { name: '西宁', pinyin: 'xining', firstLetter: 'X' },
  { name: '海东', pinyin: 'haidong', firstLetter: 'H' },
  { name: '海北', pinyin: 'haibei', firstLetter: 'H' },
  { name: '黄南', pinyin: 'huangnan', firstLetter: 'H' },
  { name: '海南', pinyin: 'hainan', firstLetter: 'H' },
  { name: '果洛', pinyin: 'guoluo', firstLetter: 'G' },
  { name: '玉树', pinyin: 'yushu', firstLetter: 'Y' },
  { name: '海西', pinyin: 'haixi', firstLetter: 'H' },

  // 宁夏
  { name: '银川', pinyin: 'yinchuan', firstLetter: 'Y' },
  { name: '石嘴山', pinyin: 'shizuishan', firstLetter: 'S' },
  { name: '吴忠', pinyin: 'wuzhong', firstLetter: 'W' },
  { name: '固原', pinyin: 'guyuan', firstLetter: 'G' },
  { name: '中卫', pinyin: 'zhongwei', firstLetter: 'Z' },

  // 新疆
  { name: '乌鲁木齐', pinyin: 'wulumuqi', firstLetter: 'W' },
  { name: '克拉玛依', pinyin: 'kelamayi', firstLetter: 'K' },
  { name: '吐鲁番', pinyin: 'tulufan', firstLetter: 'T' },
  { name: '哈密', pinyin: 'hami', firstLetter: 'H' },
  { name: '昌吉', pinyin: 'changji', firstLetter: 'C' },
  { name: '博尔塔拉', pinyin: 'boertala', firstLetter: 'B' },
  { name: '巴音郭楞', pinyin: 'bayinguoleng', firstLetter: 'B' },
  { name: '阿克苏', pinyin: 'akesu', firstLetter: 'A' },
  { name: '克孜勒苏', pinyin: 'kezilesu', firstLetter: 'K' },
  { name: '喀什', pinyin: 'kashi', firstLetter: 'K' },
  { name: '和田', pinyin: 'hetian', firstLetter: 'H' },
  { name: '伊犁', pinyin: 'yili', firstLetter: 'Y' },
  { name: '塔城', pinyin: 'tacheng', firstLetter: 'T' },
  { name: '阿勒泰', pinyin: 'aletai', firstLetter: 'A' },
  { name: '石河子', pinyin: 'shihezi', firstLetter: 'S' },
  { name: '阿拉尔', pinyin: 'alaer', firstLetter: 'A' },
  { name: '图木舒克', pinyin: 'tumushuke', firstLetter: 'T' },
  { name: '五家渠', pinyin: 'wujiaqu', firstLetter: 'W' },
  { name: '北屯', pinyin: 'beitun', firstLetter: 'B' },
  { name: '铁门关', pinyin: 'tiemenguan', firstLetter: 'T' },
  { name: '双河', pinyin: 'shuanghe', firstLetter: 'S' },
  { name: '可克达拉', pinyin: 'kekedala', firstLetter: 'K' },
  { name: '昆玉', pinyin: 'kunyu', firstLetter: 'K' },
  { name: '胡杨河', pinyin: 'huyanghe', firstLetter: 'H' }
];